Add recurrence
renzon/django_pagarme pull request #153
Opened 2020-10-07 20:28 UTC by rfdeoliveira

- Add subscriptions
- Update plans on sync and remove orphans
- Add subscriptions templates, payment relation and model admin
- Add subscription notifications
- Update readme.md

2020-10-09 13:33 UTC, walison17 commented on django_pagarme/facade.py
> +def list_plans() -> List[PagarmeItemConfig]:
Acho que a type annotation ficou errada

2020-10-09 13:33 UTC, walison17 commented on django_pagarme/management/commands/__init__.py
> +def sync_plans():
Vi que vc implementou o método de sincronização na fachada, acho que podemos remover esse método daqui

2020-10-09 14:30 UTC, renzon commented on django_pagarme/facade.py
> +def list_plans() -> List[PagarmeItemConfig]:
Verdade, deve ser um tipo diferente aqui, uma lista de planos.

2020-10-09 14:48 UTC, rfdeoliveira commented on django_pagarme/management/commands/__init__.py
> +def sync_plans():
Boa! Resolvido.

2020-10-09 14:48 UTC, rfdeoliveira commented on django_pagarme/facade.py
> +def list_plans() -> List[PagarmeItemConfig]:
Muito bom! Resolvido.

2020-10-09 14:51 UTC, rfdeoliveira commented
Corrigi a ordenação dos métodos de pagamento dos planos. Quando vem os dois da api, vem da seguinte forma `boleto,credit_card`. Assim, no django admin não aparece o método de pagamento como `Cartão de crédito ou boleto`. Para isso, deveria ser salvo no modelo da seguinte forma `credit_card,boleto`.

2020-10-09 16:02 UTC, renzon requested changes

2020-10-09 19:30 UTC, rfdeoliveira commented on django_pagarme/templates/django_pagarme/pagarme_js_form.html
> +                        country: 'br',  /* TODO: country name set by subscription is not accepted by payment with items */
O country que é gravado no customer ao gravar uma assinatura é `Brasil`, daí, ao tentar fazer um novo checkout com o mesmo profile acontece um erro dizendo que o nome do país é inválido. Acredito que dê pra resolver sem deixar fixo, porém não encontrei uma forma efetiva. Consegue reproduzir?

1. Trocar o country hardcoded pelo address.country
1. Fazer o checkout de um plano
1. Fazer o checkout de um produto avulso

2020-10-24 10:19 UTC, renzon commented on django_pagarme/templates/django_pagarme/pagarme_js_form.html
> +                        country: 'br',  /* TODO: country name set by subscription is not accepted by payment with items */
Podemos tratar a inconsistência normalizando na hora de receber os dados e salvar o Profile, criar um dicionário {'Brasil':'br'}, o que acha @rfdeoliveira

2020-10-26 22:11 UTC, rfdeoliveira commented on django_pagarme/templates/django_pagarme/pagarme_js_form.html
> +                        country: 'br',  /* TODO: country name set by subscription is not accepted by payment with items */
Boa! Vou experimentar.

2021-08-15 20:27 UTC, rfdeoliveira commented on django_pagarme/templates/django_pagarme/pagarme_js_form.html
> +                    country: 'br', /* TODO: country name set by subscription is not accepted by payment with items*/
Resolvido!

2021-08-15 20:27 UTC, rfdeoliveira commented on django_pagarme/templates/django_pagarme/pagarme_js_form.html
> +                        country: 'br',  /* TODO: country name set by subscription is not accepted by payment with items */
Resolvido!

2024-03-31 14:30 UTC, merged